Fc 13/game engine
FancyCodersYAP/UNO-fancy pull request #12
Opened 2023-03-06 17:22 UTC by Catalinadevolg

Описана механика игры (без анимации) с компьютером. Для двух и четырёх игроков.

2023-03-10 14:14 UTC, we1tkindzy commented on packages/client/src/App.css
> +* {
Я бы это перенес в styles/global.tsx

2023-03-10 14:14 UTC, we1tkindzy commented on packages/client/src/components/game/utils/EventBus.ts
> +export type Listener<T extends unknown[] = any[]> = (...args: T) => void;
Не могу найти, где используется EventBus.ts, он нужен для работы функционала?

2023-03-13 10:31 UTC, Catalinadevolg commented on packages/client/src/components/game/utils/EventBus.ts
> +export type Listener<T extends unknown[] = any[]> = (...args: T) => void;
Да, я его использую в случае событий "click uno" (когда пользователь нажимает "UNO") и "finish" (когда игра заканчивается).

2023-03-13 10:36 UTC, Catalinadevolg commented on packages/client/src/App.css
> +* {
Да, конечно. Стили в игре до конца не проработаны, поэтому пока что всё находится в App.css. В дальнейшем стили по игре вынесу в отдельный файл.

2023-03-13 15:53 UTC, Dormeh reviewed
я пока только поверхностно успел посмотреть
планирую завтра посмотреть и вникнуть детально

2023-03-13 15:53 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +import { EventBus } from '../utils/EventBus';
Катя, зачем нам EventBus в реакте тут же Redux есть и он должен следить за сотоянием приложения. Я пока поверхностно смотрю. Но state самого приложения можно использовть context либо раз уже внедрили redux то стоит привязывать состояние к нему. Все что было в прошлом модуле я так понял это поверхностный вариант.

2023-03-24 15:27 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +    this.openCard = initialPack.splice(initialPack.length - 1 - 1, 1)[0];
как насчет метода `pop` ?
если нужно взять последнюю какрту и ее удалить как я понял, то это оно.

2023-03-24 15:52 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +      const botId = this.players.find(player => player.isBot === true)?.id;
`player => player.isBot )` здесь по моему достаточно так

2023-03-24 16:26 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +  identifyEntity() {
Пока всю логику не просмотрел, но на первый взгляд  можно из массива игроков или ботов определить id бота/игра `this.players[this.currentPlayer]` или  `this.bots` создать и к нему применить в любом случае такую конструкцию лучше упростить

2023-03-24 16:29 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +      for (let i = 0; i < botCards.length; i++) {
возможно на будущее чтобы прокачать ИИ) можно сделать массив из всех вариантов и применить функцию "умного" выбора из этого массива

2023-03-24 17:03 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +  checkCard(cardFromHand: CardType) {
здесь нужна оптимизации
вынес в отдельную задачу возможно у кого-то возникнут мысли по ходу ревью
самое простое что IDE предлагает это соеденить последние два стравнения в одно `return cardFromHand.action === 'wild draw four';` убрав `return false`

2023-03-24 17:05 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +        if (attemptTakeCard === true) {
`=== true`  можно убрать

2023-03-24 17:37 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +            rightMove = false;
а зачем ты присваиваешь тут значение, если из функциии все равно выходишь?

2023-03-24 17:39 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +      for (let i = playerCards.length - 1; i >= 0; i--) {
меня посещает мысль вынести проверку возможности хода в отдельный метод, чтобы он не загромождал код этого метода

2023-03-24 17:42 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +      if (attemptTakeCard && rightMove) {
по идее если сюда дошли то проверку на право брать из колоды делать не нужно так как выше уже бы вылетели из функции и нужен ли  `rightMove` тогда  в коде? (возможно что-то упустил)

2023-03-24 17:46 UTC, Dormeh commented on packages/client/src/components/game/core/game.ts
> +      if (attemptTakeCard && rightMove) {
по-моему return тут не нужен так как дальше кода нет для этого условия

2023-03-25 11:53 UTC, bin-umar commented on packages/client/src/components/game/core/game.ts
> +      const botId = this.players.find(player => player.isBot === true)?.id;
```suggestion
      const botId = this.players.find(({ isBot }) => isBot)?.id;
```

2023-03-26 12:03 UTC, bin-umar requested changes

2023-03-27 06:22 UTC, Catalinadevolg commented on packages/client/src/pages/gamePage/gamePage.tsx
> +        }}>
Принято.
Модальные окна у нас в других ветках. У себя я сделала простые для тестирования игры, поэтому инлайн-стили - это временный код.

2023-03-27 06:22 UTC, Catalinadevolg commented on packages/client/src/pages/gamePage/gamePage.tsx
> +    document.querySelector('.btn-uno')?.classList.add('btn-uno_active');
Также хук для использования модальных окон тоже есть в другой ветке. Эти функции написаны для тестирования игры.

2023-03-27 06:22 UTC, Catalinadevolg commented on packages/client/src/components/game/core/controller.ts
> +  unoClick() {
Подразумевается клик по кнопке 'UNO'

2023-03-27 06:23 UTC, Catalinadevolg commented on packages/client/src/components/game/utils/data.ts
В этом файле на 500+ строк один массив с данными 108-и карт игры. К сожалению, не могу разделить.

2023-03-27 06:23 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
Спасибо за комментарии и замечания! Постараюсь уменьшить файл и внесу правки по остальным моментам.

2023-03-28 18:19 UTC, bin-umar commented on packages/client/src/components/game/utils/data.ts
Ок, это можно оставить как есть.

2023-04-03 21:11 UTC, bin-umar approved these changes

2023-04-05 14:21 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
> +    for (let i = 0; i < cardsForDistribution.length; i++) {
Больше не храню карты в player'е, раньше они были и в player'е, и в entity.
Эти строки не актуальны.

2023-04-05 14:22 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
> +  identifyEntity() {
Создала TwoPlayerLayers и FourPlayerLayers для определения сущности игрока, который ходит

2023-04-05 14:22 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
> +      for (let i = 0; i < botCards.length; i++) {
Я себе изначально представляла такой способ) Но этот вариант, конечно, проще, работы меньше.

2023-04-05 14:22 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
> +            rightMove = false;
Когда переделывала, снова добавила эту же переменную. Потом прочитала твой комментарий, поняла, что она действительно не нужна)

2023-04-05 14:27 UTC, Catalinadevolg commented on packages/client/src/pages/gamePage/gamePage.tsx
> +    if (modal) modal.style.display = 'none';
Везде с if добавила скобки

2023-04-05 14:28 UTC, Catalinadevolg commented on packages/client/src/pages/gamePage/gamePage.tsx
> +  };
Добавила на gamePage модальные окна, которые делал другой член команды, теперь эти функции не нужны. Удалила.

2023-04-05 14:29 UTC, Catalinadevolg commented on packages/client/src/components/game/entities/Entity.ts
> +    }
Использовала switch в функциях расчёта (calculates.ts). Кажется, наиболее подходящая конструкция в этих функциях.

2023-04-05 14:32 UTC, Catalinadevolg commented on packages/client/src/components/game/core/game.ts
Файл Game всё ещё объёмный, но по крайней мере минус 100 строк и github в PR его раскрывает)

2023-04-06 17:21 UTC, bin-umar approved these changes

2023-04-07 08:07 UTC, Catalinadevolg commented on packages/client/src/game/utils/drawCard.ts
> +  if (x && y) ctx.clearRect(x, y, BASE_WIDTH_CARD, BASE_HEIGHT_CARD);
Очень хочется сокращать большие файлы)
Но if читабельнее, поэтому оставила if и добавила скобки.

2023-04-07 08:17 UTC, bin-umar commented on packages/client/src/game/utils/helpers.ts
> +export function shuffle(array: unknown[]) {
Давай попробуем добавить дженерик, в таком случае тебе не понадобиться при каждом вызове сделать `as SomeType`

2023-04-07 08:26 UTC, bin-umar commented on packages/client/src/game/utils/helpers.ts
> +export function shuffle(array: unknown[]) {
```suggestion
export function shuffle<T extends unkown[]>(array: T): T {
```

P.S. Псевдокод

2023-04-07 11:02 UTC, Catalinadevolg commented on packages/client/src/game/utils/helpers.ts
> +export function shuffle(array: unknown[]) {
Спасибо за помощь!
Навело на мысль как избавиться ещё от нескольких as SomeType в HandEntity. Вроде бы получилось.

2023-04-07 11:20 UTC, bin-umar commented on packages/client/src/game/Controller.ts
> +      console.log('Ход другого игрока');
Для чего нужны эти логи?

2023-04-07 11:48 UTC, Catalinadevolg commented on packages/client/src/game/Controller.ts
> +      console.log('Ход другого игрока');
Все логи для теста игры. Сейчас они в большинстве своём не несут пользы, но я бы оставила их до мёрджа в main.

2023-04-07 12:25 UTC, bin-umar approved these changes
Основные замечания это по улучшение качество кода с использованием [Советы по стилю кода](https://learn.javascript.ru/coding-style) и typescript по максимум

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/utils/compareCards.ts
> +) => {
И необходимо наименовать так, чтобы было понятно, а что конкретно сравнивает?

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +      if (compareCards(card, this.table.getUpcard(), this.activeColor)) {
Для повышения читабельности кода, лучше такие сложные вызовы вывести в отдельную переменную, и проверят его
```suggestion
      const isCardsSomething = compareCards(card, this.table.getUpcard(), this.activeColor)
      if (isCardsSomething) {
```

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +      const card = botCards[i];
Попробуй лучше использовать for of
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
```suggestion
    for (const card of botCards) {
```

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +      } else {
Напоминаю про уровни вложенности https://learn.javascript.ru/coding-style#urovni-vlozhennosti

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +          }
Если делаешь `return` то `else` уже не нужен

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +    }
Вместо 5 if-ов на card.action лучше сделать switch case

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +        this.clockwiseMovement = this.clockwiseMovement === true ? false : true;
```suggestion
        this.clockwiseMovement = !this.clockwiseMovement;
```

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +    }
Ещё раз про уровни вложенности. Например давай тут я помогу
```suggestion
    if (countCards !== 1) {
      return;
    }

    // Тут надо дават правильное название compareCards-у
    const isCardsSomething = compareCards(cards[0], this.table.getUpcard(), this.activeColor)
    if (!isCardsSomething) {
      // Если карта не подходит, переход хода
      this.moveLine();
      return;
    }

    const { isBot } = this.players[this.activePlayerId];
    if (!isBot) {
      // Если ход юзера, ждём клик
      console.log('Можно скинуть карту');
      return;
    }

    // Если ход бота, делаем за него ход
    console.log('Бот через секунду скинет карту');

    const card = activePlayer.cards.at(-1);
    if (!card) {
      return;
    }

    setTimeout(() => {
      this.discardCard(card);
    }, 1000);
```

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +    }
Т.е. надо стараться писать код как можно плавнее, это сильно упрощает когнитивную сложность кода.

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +  getActivePlayer() {
Вовзращаемый тип

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/Game.ts
> +  getUnoClick() {
почему метод называется get если ничего не возвращает?

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/entities/Entity.ts
> +  colorBox: HTMLDivElement | null = null;
```suggestion
  private layer!: HTMLDivElement;
  private context!: CanvasRenderingContext2D;
  private name!: HTMLParagraphElement;
  private colorBox: HTMLDivElement | null = null;
```
Лучше явно указать что это приватные.

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/utils/compareCards.ts
> +  if (upcard.color === '#1F1D1E') {
Проверка на произвольные строки не очень хорошая практика, тем более что это цвет, его значение может быть и `#1f1d1e`. Поэтому такие вещи всё надо структуризировать тайспскриптом

2023-04-07 12:25 UTC, bin-umar commented on packages/client/src/game/utils/createElements.ts
> +) => {
return type

2023-04-10 12:35 UTC, Catalinadevolg commented on packages/client/src/game/Controller.ts
> +  tableClick(clickPos: Record<string, number>) {
Создала тип

2023-04-10 12:36 UTC, Catalinadevolg commented on packages/client/src/game/Game.ts
> +    let zIndex = 10;
Добавила константу

2023-04-10 12:40 UTC, Catalinadevolg commented on packages/client/src/game/utils/compareCards.ts
> +) => {
Переименовала функцию.
У утилит прописала возвращаемый тип

2023-04-10 12:59 UTC, Catalinadevolg commented on packages/client/src/game/Game.ts
> +        entityName as HandEntityTypes,
Не получилось избавиться от `as HandEntityTypes`.
`FourPlayerLayers[i]` возвращает тип string, а HandEntity принимает entityName с типом `HandEntityTypes = keyof typeof FourPlayerLayers`. Не сообразила, как исправить, чтобы убрать `as HandEntityTypes`

2023-04-10 15:34 UTC, bin-umar commented on packages/client/src/game/entities/Entity.ts
> +  getLayer() {
```suggestion
  getLayer(): HTMLDivElement {
```

2023-04-13 07:37 UTC, we1tkindzy approved these changes

2023-04-14 08:26 UTC, merged