Fc 19 main page
FancyCodersYAP/UNO-fancy pull request #15
Opened 2023-03-12 16:16 UTC by MariAnnaMari

### Какую задачу решаем
1) Добавила главную страницу. Модальные окна по нажатию на кнопки "Начать игру" и "Правила" не стала добавлять, так как компонент StartGame решили дорабатывать.
2) Изменён компонент Button: 
- добавлен пропс disignType?: 'primary' | 'secondary' | 'alternate', который отвечает за цвет кнопки, по умолчанию 'primary';
- добавлен пропс size?: 'small' | 'middle' | 'large', который отвечает за размер кнопки, по умолчанию 'middle' (возможно small нам и не нужен??).
3) Добавлено меню в хедер 

### Скриншоты/видяшка (если есть)
<img width="1264" alt="Снимок экрана 2023-03-12 в 19 02 04" src="https://user-images.githubusercontent.com/11438689/224557636-cdb664c8-341c-4fa5-82fa-4cb79fcd527b.png">

### TBD (если есть)

2023-03-13 09:10 UTC, MariAnnaMari commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
да, я не смогла применить backdrop-filter, @Dormeh посмотрит, что можно сделать.

2023-03-13 11:37 UTC, we1tkindzy commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
Кажется это свойство применяется только с background:
https://kolosek.com/css-blend-mode/

2023-03-14 11:23 UTC, Catalinadevolg commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
Получается, что на большом логотипе тоже срабатывает handleClick (и курсор pointer соответственно). Думаю, здесь обработка клика не нужна, учитывая что мы и так на главной.

2023-03-14 11:31 UTC, Catalinadevolg commented on packages/client/src/components/Header/Header.tsx
> +        ))}
Тут реакт предупреждает, что элементам нужно ключи добавить.
https://reactjs.org/docs/lists-and-keys.html#keys
![image](https://user-images.githubusercontent.com/114286265/224987581-d45bb903-ca07-45eb-b42d-79b3b4715854.png)

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/components/Header/Header.tsx
> +      <StFlexAlighItemCenter gap={20}>
я бы сделал отдельный компонент `StNavMenu`а не с хэдером этот функционал связывал чтобы не перередеривать весь хэдер , но это так  мелочи

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/components/Logo/Logo.tsx
> +    ? 'src/assets/img/colorLogo.png'
может не будет связывать большой лого и маленький в хэдере в одном компоненте? так как большой носит функционал обычной картинки и его можно положить в какой-нибудь StImageBox и кликать для навигации по нему точно не будем)

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/components/Modal/Modal.tsx
> +            <StButtonCloseModal onClick={toggle}>X</StButtonCloseModal>
'X' уже можно взять из макета как svg

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/components/Modal/Modal.tsx
> +            <StButtonCloseModal onClick={toggle}>X</StButtonCloseModal>
по желанию

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
я поправлю потом давайте оставим пока

2023-03-14 12:14 UTC, Dormeh commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
я выше написал, что их лучше разделить

2023-03-14 12:36 UTC, Dormeh commented on packages/client/src/components/Button/style.tsx
> +  padding: ${(props: ButtonProps) => {
я бы не стал делать из нашей кнопки супергероя вот честно) лучше сделать ей родственников в этом же файле по ситуации

2023-03-14 17:10 UTC, MariAnnaMari commented on packages/client/src/components/Header/Header.tsx
> +      <StFlexAlighItemCenter gap={20}>
Создала отдельный компонент NavMenu

2023-03-14 17:33 UTC, MariAnnaMari commented on packages/client/src/components/Logo/Logo.tsx
> +    ? 'src/assets/img/colorLogo.png'
Разделила лого в хедере и на главной странице

2023-03-14 17:33 UTC, MariAnnaMari commented on packages/client/src/components/Header/Header.tsx
> +        ))}
Ключ добавила

2023-03-14 17:34 UTC, MariAnnaMari commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <Logo size={350} />
Разделила лого в хедере и на главной странице

2023-03-14 18:00 UTC, MariAnnaMari commented on packages/client/src/components/Modal/Modal.tsx
> +            <StButtonCloseModal onClick={toggle}>X</StButtonCloseModal>
добавила иконку

2023-03-15 07:40 UTC, Catalinadevolg commented on packages/client/src/styles/global.tsx
>  `;
Всё супер!
Только в описании не хватает line-height.

2023-03-15 21:07 UTC, bin-umar commented on packages/client/src/utils/constants.tsx
> +export const DESCRIPTION =
`DESCRIPTION_OF_WHAT`?

2023-03-15 22:29 UTC, bin-umar requested changes

2023-03-15 22:29 UTC, bin-umar commented
Порешай конфликты пжл.

2023-03-16 16:59 UTC, MariAnnaMari commented on packages/client/src/styles/variables/types.ts
> +  COLOR_ELEMENT_ALTERNATE: string;
решили ввести ещё дополнительный цвет для кнопки. Как лучше назвать?

2023-03-16 17:04 UTC, MariAnnaMari commented on packages/client/src/styles/global.tsx
> +  gap: ${(props: { gap?: number }) => (props?.gap ? props?.gap + 'px' : 0)};
исправлено

2023-03-16 17:04 UTC, MariAnnaMari commented on packages/client/src/styles/global.tsx
>      props?.width ? props?.width + 'px' : 'auto'};
исправлено

2023-03-16 17:13 UTC, MariAnnaMari commented on packages/client/src/components/Logo/Logo.tsx
> +  height: ${(props: LogoProps) => props?.size}px;
дефолтное значение добавлено

2023-03-16 18:01 UTC, MariAnnaMari commented on packages/client/src/utils/constants.tsx
> +export const DESCRIPTION =
переименовала в GAME_DESCRIPTION

2023-03-17 17:51 UTC, Dormeh commented on packages/client/src/styles/variables/types.ts
> +  COLOR_ELEMENT_ALTERNATE: string;
ALTERNATE звучит как-то внушительнее что ли чем teritary поэтому посовещались и выбрали

2023-03-17 17:55 UTC, Dormeh approved these changes

2023-03-17 18:05 UTC, merged