Fc 18 authentication api
FancyCodersYAP/UNO-fancy pull request #17
Opened 2023-03-15 19:13 UTC by Dormeh

api авторизации и регистрации интегрирован через redux store
конфигурация store
подключил взаимодействие со страницами LoginPage RegistrationPage
навигация при авторизации

2023-03-21 11:43 UTC, bin-umar requested changes

2023-03-21 11:43 UTC, bin-umar commented on .env
Не стоит .env выкладывать на гит, для этого надо создать .env.sample и в Readme указать что скопируйте его в .env файл

2023-03-21 11:43 UTC, bin-umar commented on packages/client/src/App.tsx
> +      const url = `http://localhost:${__APP_ENV__.SERVER_PORT}`;
лучше будет вывести это (url) в constants

2023-03-21 11:43 UTC, bin-umar commented on packages/client/src/components/Layout/MainLayout.tsx
> +  const [, , isLoading] = authState();
можно из authState возвращать объект, а не массив, чтобы получить нужную переменную без костылей):
```suggestion
  const { isLoading } = authState();
```

2023-03-21 11:43 UTC, bin-umar commented on packages/client/src/components/PrivateRoute/PrivateRoute.tsx
>  const PrivateRoute: Props = ({ children }) => {
чем отличается `AuthRoute` от `PrivateRoute`?

2023-03-21 11:43 UTC, bin-umar commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
вместо того чтобы каждый раз его указывать, лучше попробуй добавить interceptor (middleware) https://axios-http.com/docs/interceptors
Будет примерно так:
```ts
axios.interceptors.request.use(
  function(config) {
    config.withCredentials = true;
    return config;
  },
  function(error) {
    return Promise.reject(error);
  }
);
```

2023-03-21 19:14 UTC, Dormeh commented on packages/client/src/components/PrivateRoute/PrivateRoute.tsx
>  const PrivateRoute: Props = ({ children }) => {
один редиректит на авторизацию если не авторизован. Athroute кидает на главную если в histrory остался переход на логин или регистрацию либо пользователь сам из адресной строки попытается попасть на авторизацию
также перкинет на главную

2023-03-22 14:51 UTC, Dormeh commented on packages/client/src/components/AuthRoute/AuthRote.tsx
> +  children: any;
исправил

2023-03-22 14:52 UTC, Dormeh commented on packages/client/src/components/Form/Form.tsx
> +import { RegFormParams } from '../../pages/RegistrationPage/RegistrationPage';
исправил

2023-03-22 14:53 UTC, Dormeh commented on .env
добавил в gitignore

2023-03-22 14:56 UTC, Dormeh commented on packages/client/src/App.tsx
> +      const url = `http://localhost:${__APP_ENV__.SERVER_PORT}`;
это нам в таком виде проект пришел от практикума я только добавил в конфиг переменную окружения, но сейчас API_ENDPOINT переделал на константу, а этот кусок кода вернул как было.

2023-03-22 14:57 UTC, Dormeh commented on packages/client/src/App.tsx
> +      const url = `http://localhost:${__APP_ENV__.SERVER_PORT}`;
Если рекомендуешь совсем избавится от этого, то я пропишу порт в константы

2023-03-22 15:03 UTC, Dormeh commented on packages/client/src/components/Layout/MainLayout.tsx
> +  const [, , isLoading] = authState();
исправил

2023-03-22 15:14 UTC, Dormeh commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
по config понял а по error нет
`  function(error) {
    return Promise.reject(error);
  }
`
что это даст?
мне нужно обязательно ошибку отправить через `rejectWithValue` а ее я получаю только внутри экшена

2023-03-22 15:15 UTC, Dormeh commented on packages/client/src/store/auth/actions.ts
> +      return await dispatch(fetchAuth());
исправил

2023-03-22 15:16 UTC, Dormeh commented on packages/client/src/utils/apiCheckError.ts
> +  if (res && (res.status + '').slice(0, 2) === '40' && 'reason' in res.data) {
исправил

2023-03-22 16:19 UTC, bin-umar commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
`function(error) { return Promise.reject(error); }`

Это просто прокидывание дальше не разбираясь в ошибку

2023-03-22 16:19 UTC, bin-umar commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
Это может быть полезным если ты например хочешь собирать метрики для ошибок, в этом случае сюда пишется логика сбора метрик по axios ошибкам.

2023-03-22 16:20 UTC, bin-umar commented on .env
Необходимо удалить его из PR тоже

2023-03-22 16:24 UTC, bin-umar commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +      <p style={{ color: 'red', margin: 0, padding: 0 }}>{authError}</p>
Это можешь пока оставить если не хочется исправить сейчас, но в идеале должен быть либо отдельным маленьким компонентом, либо хотя бы не писать инлайн стили

2023-03-22 16:28 UTC, bin-umar commented on packages/client/src/App.tsx
> +      const url = `http://localhost:${__APP_ENV__.SERVER_PORT}`;
Я скорее про всю переменную  `const url = 'http://localhost:${__APP_ENV__.SERVER_PORT}';`
Но можешь пока оставить, вынесим по необходимости

2023-03-22 17:56 UTC, Dormeh commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +      <p style={{ color: 'red', margin: 0, padding: 0 }}>{authError}</p>
да я в комментарии оставил инфо, что это тестовый компонент для проверки отображения состояния ошибки и в дальнейшем там будет самостоятельный компонент ошибки без инлайнстилей конечно же

2023-03-22 18:02 UTC, Dormeh commented on .env
сделано

2023-03-22 18:07 UTC, Dormeh commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
понял т.е. если режект я обработаю от axios один раз и дальше он не пробросит мне? Или я могу ошибку промежуточно обработать (логирование и пр) допустим и пробросить дальше по цепочке?
Если в этом смысл, то понял полезная вещь на будущее учту.

2023-03-22 18:08 UTC, Dormeh commented on packages/client/src/App.tsx
> +      const url = `http://localhost:${__APP_ENV__.SERVER_PORT}`;
окей я пока вернул первоначальное состояние и апи яндекса вынес в константу

2023-03-23 10:04 UTC, bin-umar commented on packages/client/src/store/auth/actions.ts
> +        withCredentials: true,
Да

2023-03-23 10:07 UTC, bin-umar approved these changes

2023-03-23 15:49 UTC, MariAnnaMari approved these changes

2023-03-23 16:34 UTC, merged