FC-58 Status bar and FC-59 Fullscreen API
FancyCodersYAP/UNO-fancy pull request #23
Opened 2023-03-20 10:41 UTC by Catalinadevolg

Добавлен background на GameLayout
Добавлен status bar с кнопками для переключения fullscreen и выхода из игры.
Также в статус баре будет отображаться время (сколько уже длится игра). Пока что на его месте заглушка.

Фиолетовый флажок добавлен временно для переключения состояния статус бара в зависимости от того, находится ли пользователь уже в игре или он видит модальные окна.

2023-04-05 07:08 UTC, juliastetskaya commented on packages/client/src/components/StatusBar/style.tsx
> +  float: right;
`flex-direction: row` свойство по-умолчанию, можно не прописывать

Какую роль здесь выполняет `float: right`?

2023-04-05 07:08 UTC, juliastetskaya commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: '10px';
Значение свойства должно быть без кавычек. Сейчас оно не применяется

2023-04-05 07:47 UTC, we1tkindzy requested changes

2023-04-05 07:47 UTC, we1tkindzy commented on packages/client/src/components/StatusBar/style.tsx
> +export const StyledButtonStatusBar = styled(StButtonStatusBar)`
К примеру, добавим четвертую кнопку, тогда нужно будет все менять вручную. Лучше сделать всем кнопкам ```margin-right: 10px;```  в StButtonStatusBar, а последней его обнулить:
``` 
&:last-child {
    margin-right: 0;
}; 
```

2023-04-07 07:25 UTC, Catalinadevolg commented on packages/client/src/components/Layout/GameLayout.tsx
> +    <>{children ?? <Outlet />}</>
Поправила

2023-04-07 07:25 UTC, Catalinadevolg commented on packages/client/src/assets/icons/statusBarSVG.tsx
> +
Готово

2023-04-07 07:26 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/StatusBar.tsx
> +    isGame === false ? setGame(true) : setGame(false);
Принято.
Но строка была только для теста. Удалила

2023-04-07 07:27 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
> +  float: right;
flex-direction убрала.
float: right использовала видимо чтобы прижать вправо, но не помню, почему не использовала свойства flex. Заменила на justify-content

2023-04-07 07:28 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: '10px';
Убрала кавычки

2023-04-07 07:28 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
> +export const StyledButtonStatusBar = styled(StButtonStatusBar)`
Однозначно!
Заменила.

2023-04-07 16:32 UTC, we1tkindzy commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: 5px;
мне и так нравится, но мне говорили, что лучше так: ``` margin:  0 5px 0 0; ```

2023-04-08 15:41 UTC, Dormeh commented on packages/client/src/assets/icons/fullscreen.svg
> +    viewBox="0 0 24 24"
вьюбокс нужен если не собираешься масштабировать размер иконки

2023-04-08 16:36 UTC, Dormeh commented on packages/client/src/components/Layout/GameLayout.tsx
> +  background: radial-gradient(#b0c9d7, #3a5d70);
этот бэкграунд колор можно убрать в переменные цветов

2023-04-08 16:47 UTC, Dormeh commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: 5px;
тут и говорить нечего даже IDE ругается нужно писать `margin: 0 5px 0 0;`

2023-04-08 16:51 UTC, Dormeh commented
![image](https://user-images.githubusercontent.com/54811697/230733294-047c2d7b-460e-4ab6-b573-d66a37bca89b.png)
в качестве предложения предложил бы в строку сделать а не в столбик(если у нас таймер всё же останется)

2023-04-08 17:06 UTC, Dormeh commented on packages/client/src/store/store.ts
>    AUTH: authSlice,
удален

2023-04-09 20:35 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: 5px;
Поправила

2023-04-09 20:36 UTC, Catalinadevolg commented on packages/client/src/components/Layout/GameLayout.tsx
> +  background: radial-gradient(#b0c9d7, #3a5d70);
Добавила в переменные

2023-04-09 20:36 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: 5px;
Поправила

2023-04-10 12:26 UTC, Dormeh commented on packages/client/src/contexts/GameContext.tsx
> +  return context;
`  return useContext(GameContext);
`
а зачем ты проверяешь на существование у тебя же дефолтный контекст всегда есть ?

2023-04-10 12:43 UTC, Dormeh commented on packages/client/src/components/Layout/GameLayout.tsx
> +        <StatusBar />
В итоге я не понял будет ли isGame использоваться ниже по иерархии если нет и только для лежащего на поверхности `StatusBar` то смысл использования доп инстументов для меня не скрыт

2023-04-11 19:18 UTC, Dormeh approved these changes

2023-04-12 06:26 UTC, Catalinadevolg commented on packages/client/src/contexts/GameContext.tsx
> +  return context;
Удалила проверку

2023-04-12 21:59 UTC, bin-umar approved these changes
Всё написано чётко и красиво!!) Молодцом;

2023-04-12 22:01 UTC, bin-umar commented on packages/client/src/components/StatusBar/style.tsx
> +  margin-right: 5px;
Можно ещё и так: `margin: 0 5px 0;` :)

2023-04-12 22:03 UTC, bin-umar commented
@Dormeh @juliastetskaya @we1tkindzy ребята, очень хорошие замечании!) Рад что справляетесь и без меня 🙂

2023-04-13 07:34 UTC, we1tkindzy approved these changes

2023-04-13 15:45 UTC, merged