FC-82: Audio API
FancyCodersYAP/UNO-fancy pull request #37
Opened 2023-04-14 08:04 UTC by Catalinadevolg

### Добавлено аудио сопровождение в игре

Добавлены иконки в статус бар для смены беззвучного режима, а также для установки паузы.

![image](https://user-images.githubusercontent.com/114286265/231982399-88021869-c0d4-49a9-8501-4ce7ab7d11e5.png)

2023-04-20 08:56 UTC, we1tkindzy requested changes

2023-04-20 08:56 UTC, we1tkindzy commented on packages/client/src/components/StatusBar/statusBarSVG.tsx
> +export const PauseSVG = (): JSX.Element => (
Предлагаю во время паузы менять иконку паузы на иконку "возобновить" ▶

2023-04-20 08:56 UTC, we1tkindzy commented on packages/client/src/game/services/audioManager.ts
> +  const stopAudio = () => {
Если вернуться на главную через стрелку браузера, то музыка и звуки карт не прекращают играть

2023-04-20 08:56 UTC, we1tkindzy commented on packages/client/src/game/utils/sounds.ts
> +export const SoundList: SoundListType = {
Можно еще добавить звук, если пользователь не успел нажать на "uno", то проигрывается что-то типо: "Too slow!"

2023-04-20 08:56 UTC, we1tkindzy commented on packages/client/src/game/services/audioManager.ts
> +  /* Возможно стоит выводить модалку при включении паузы */
Можно сделать затемнение экрана (как у всех модалок) и посередине большую белую кнопку ▶

2023-04-20 13:28 UTC, Dormeh commented on packages/client/src/components/Layout/GameLayout.tsx
> +import { audioManager } from 'game/services/audioManager';
будет использоваться на этой странице?

2023-04-20 13:36 UTC, Dormeh commented on packages/client/src/components/StatusBar/StatusBar.tsx
> +          <StButtonStatusBar
зачем создаются эти компоненты c свг? кнопка может принять пропс в виде строки и туда импортировать  свг и создавать для этого отдельный копонент (в итоге несколько компонентов) не вижу смысла
Катя, посмотри пожалуйста как Валенин делает и как во всем проекте это реализовано у нас уже есть кнопки которые внутри имеют свг возмоно можно наследовавться или хотябы перенять стиль

2023-04-20 13:37 UTC, Dormeh commented on packages/client/src/components/StatusBar/statusBarSVG.tsx
> +  <svg width="25px" height="25px" viewBox="-40.96 -40.96 593.92 593.92">
всю свг разметку нужно перенести в асеты

2023-04-20 14:05 UTC, Dormeh commented on packages/client/src/components/StatusBar/statusBarSVG.tsx
> +  <svg width="25px" height="25px" viewBox="-40.96 -40.96 593.92 593.92">
```  <svg
    width="20"
    height="20"
    viewBox="0 0 36 36"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
    <path
      d="M0 12V24H8L18 34V1.99996L8 12H0ZM27 18C27 14.47 24.96 11.42 22 9.94996V26.06C24.96 24.58 27 21.53 27 18ZM22 0.459961V4.58996C27.78 6.30996 32 11.66 32 18C32 24.34 27.78 29.69 22 31.41V35.54C30.01 33.72 36 26.57 36 18C36 9.42996 30.01 2.27996 22 0.459961Z"
      fill="currentColor"
    />
  </svg>
  ```
пример чистого свг
у тебя свг взяты из чужих проектов с айдишками и доп настройками они нам не нужны

2023-04-20 14:12 UTC, Dormeh commented on packages/client/src/components/StatusBar/statusBarSVG.tsx
> +  <svg width="25px" height="25px" viewBox="-40.96 -40.96 593.92 593.92">
```  
 <svg width="25" height="25" viewBox="-40.96 -40.96 593.92 593.92">
    <path d="M361.299413,341.610667 L328.014293,314.98176 C402.206933,233.906133 402.206933,109.96608 328.013013,28.8906667 L361.298133,2.26304 C447.910187,98.97536 447.908907,244.898347 361.299413,341.610667 Z M276.912853,69.77216 L243.588693,96.4309333 C283.38432,138.998613 283.38304,204.87488 243.589973,247.44256 L276.914133,274.101333 C329.118507,215.880107 329.118507,127.992107 276.912853,69.77216 Z M191.749973,1.42108547e-14 L80.8957867,87.2292267 L7.10542736e-15,87.2292267 L7.10542736e-15,257.895893 L81.0208,257.895893 L191.749973,343.35424 L191.749973,1.42108547e-14 L191.749973,1.42108547e-14 Z M42.6666667,129.895893 L95.6874667,129.895893 L149.083307,87.8749867 L149.083307,256.520747 L95.5624533,215.229227 L42.6666667,215.229227 L42.6666667,129.895893 Z"></path>
  </svg>
  ```
твою тоже можно обрезать

2023-04-20 15:11 UTC, Dormeh commented on packages/client/src/game/services/audioManager.ts
> +    if (Object.keys(audioList).length === 0) return;
можно так `!Object.keys(audioList).length`

2023-04-23 18:52 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +  const stopAudio = () => {
Поправила этот момент

2023-04-23 18:53 UTC, Catalinadevolg commented on packages/client/src/game/utils/sounds.ts
> +export const SoundList: SoundListType = {
Добавила звук для пропуска нажатия на кнопку

2023-04-23 18:54 UTC, Catalinadevolg commented on packages/client/src/components/Layout/GameLayout.tsx
> +import { audioManager } from 'game/services/audioManager';
нет, удалила

2023-04-23 18:56 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/style.tsx
>    &:hover svg {
стили для active действуют только в момент нажатия. ButtonStatusBarActive используется в зависимости от состояния: если, например, звук включен, иконка белая, если выключен - сиреневая.

2023-04-23 18:56 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +    if (Object.keys(audioList).length === 0) return;
объединила условия

2023-04-23 18:58 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/StatusBar.tsx
> +          <StButtonStatusBar
Все svg перенесла в assets, импортирую через use, как в большей части проекта

2023-04-23 18:59 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/statusBarSVG.tsx
> +  <svg width="25px" height="25px" viewBox="-40.96 -40.96 593.92 593.92">
Почистила

2023-04-23 22:13 UTC, bin-umar approved these changes

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/Controller.ts
> +    this.game.on('skip click uno', callback);
События лучше вывести на типы или enum, так как строками есть шансы выстрелить себе в ногу

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +  };
Почему метод называется `changeVolume` но делает только mute?

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +  const stopAudio = () => {
Надо подписаться на событии и вызвать метод stopAudio

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +  const playSound = (name: SoundNameType) => {
где-то audio: stopAudio, где-то sound: playSound. Надо чтобы было единообразие.

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +    setAudioList({ ...list });
?

2023-04-23 22:13 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +  const playFinish = () => {
что за finish?

2023-04-24 06:31 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +  const playSound = (name: SoundNameType) => {
Хотелось разделить эти функции. Где sound, функция работает с одним звуком, где аудио - со всеми.
Если не понятно, может стоит audio заменить на music

2023-04-24 06:31 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +  const playFinish = () => {
Когда кто-то побеждает, игра заканчивается, проигрывает мелодия финиша игры. Но юзер может сыграть ещё раз не уходя со страницы, поэтому здесь я не применяю stopAudio

2023-04-24 07:24 UTC, bin-umar commented on packages/client/src/game/services/audioManager.ts
> +  };
По сути это mute и unmute, changeVolume означает что можно регулировать громкость от 0 до 100

2023-04-24 07:33 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +  };
Я согласна.
Заменю тогда на muteOrUnmuteAudio

2023-04-24 09:44 UTC, we1tkindzy approved these changes

2023-04-24 09:44 UTC, we1tkindzy commented on packages/client/src/components/StatusBar/StatusBar.tsx
>    const toggleFullScreen = () => {
Если выйти из полноэкранного режима через Esc, то иконка не меняется

2023-04-24 11:18 UTC, Catalinadevolg commented on packages/client/src/game/Controller.ts
> +    this.game.on('skip click uno', callback);
Добавила enum с событиями

2023-04-24 11:19 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +    setAudioList({ ...list });
Удалила list )

2023-04-24 15:12 UTC, Dormeh commented on packages/client/src/pages/GamePage/PlayModal.tsx
> +export const PlayModal = ({ resumeGame }: PauseModalPropsType) => (
это же не страница, а компонент
давай его в компоненты отправим в папку Modal посколько это вариация из модалки для паузы

2023-04-24 15:17 UTC, Dormeh approved these changes

2023-04-25 05:10 UTC, Catalinadevolg commented on packages/client/src/game/services/audioManager.ts
> +  const stopAudio = () => {
Не пойму на какие события(
Я при загрузке страницы создаю аудио элементы и удаляю их только при выходе со страницы игры.
Когда игра заканчивается, юзер может сыграть ещё раз, поэтому звуки нам ещё нужны.

2023-04-25 06:54 UTC, Catalinadevolg commented on packages/client/src/components/StatusBar/StatusBar.tsx
>    const toggleFullScreen = () => {
Как писала в чате, поправлю в следующем PR

2023-04-25 07:15 UTC, merged