FC-84 avatar modal
FancyCodersYAP/UNO-fancy pull request #43
Opened 2023-04-22 10:33 UTC by we1tkindzy

Создает модальное окно со сменой аватара (components/AvatarModalWindow).

![image](https://user-images.githubusercontent.com/58230964/233778806-1c7b52d5-997f-4cf4-85bd-8717ba2c5a10.png)

2023-05-03 12:45 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +const AvatarModalWindow = ({ handleCloseModal }: AvatarModal) => {
у нас нет кнопки закрытия тут стоит сделать либо крестик либо по нажатию мимо окна закрытие хотя это форма но не страшно так как юзер ничгео не печатал

2023-05-03 12:46 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        <StAvatarInput
здесь стоит указать какие файлы загружаем чтобы не вываливало весь список файлов

2023-05-03 12:47 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +  border: 1px solid #fffefe;
цвет давай возьмем из констант

2023-05-03 12:58 UTC, Dormeh requested changes

2023-05-03 12:58 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +      <Button onClick={handleCloseModal} text="Установить фотографию" />
нажатие на эту кнопку точно должно закрывать модальное окно ?

2023-05-03 12:58 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +      dispatch(fetchAvatarChange(formData));
мы не отправляем по загрузке ты видимо не уловил смысл этого компонента
в таком виде компонент уже сделан
Прочитай задачу, если не поняно спроси в чате.
Пока этот компонет, что получился несет ненужную нагрузку.

2023-05-03 13:19 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +      dispatch(fetchAvatarChange(formData));
добавил пояснение к задаче в лайнере

2023-05-05 17:17 UTC, Catalinadevolg commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +      return handleCloseModal();
Может не стоит закрывать окно, если аватар не выбран?

2023-05-05 18:05 UTC, Catalinadevolg commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +    const avatarError = document.querySelector('#avatarError') as HTMLElement;
Можно использовать useRef, как предлагал Джахонгир в PR с модалкой addTopic

2023-05-05 18:08 UTC, Catalinadevolg commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
>  const API_RESOURCES = `${REDIRECT_URL}/api/v2/resources`;
Лучше вынести в константы стора

2023-05-08 17:25 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        <StAvatarInput
![image](https://user-images.githubusercontent.com/54811697/236889982-14607533-9a52-431d-a863-6f019788ad42.png)
по прежнему предлагает выбрать любой файл а не картинку

2023-05-08 17:28 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        avatarError.textContent = `размер файла ${sizeKb} допустимый не более 1Мб`;
![image](https://user-images.githubusercontent.com/54811697/236890411-d6a60aeb-5557-44d1-a22a-25cdb6b7840b.png)
возможно лучше использовать цвет по краснее из констант это же предупреждение

2023-05-08 18:00 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        onChange={onAvatarChange}
accept="image/png, image/gif, image/jpeg"

2023-05-08 18:05 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
уже кучу раз видел это в стилях стоит это значение вынести в константы

2023-05-08 18:06 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +  bottom: -25px;
я бы использовал %

2023-05-09 15:17 UTC, we1tkindzy commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        avatarError.textContent = `размер файла ${sizeKb} допустимый не более 1Мб`;
В формах тогда тоже нужно менять цвет предупреждений? делал по ним

2023-05-09 19:56 UTC, Catalinadevolg approved these changes

2023-05-10 15:14 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +        avatarError.textContent = `размер файла ${sizeKb} допустимый не более 1Мб`;
в формах пусть останется думаю, а  тут лучше добавить предупреждения красным

2023-05-10 15:37 UTC, we1tkindzy commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +  bottom: -25px;
Например ``` bottom: -25%; ```, и если элементу (в данном случае StAvatarInputWrapper) задать определенную высоту, то уведомление поедет. А если задать фиксированный отступ вниз ``` bottom: -25px; ```, то будет хорошо при любой высоте элемента

2023-05-10 16:41 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +  bottom: -25px;
зачем 25% то ?
нужно установить %% от в пропорции от величины родителя

2023-05-10 16:43 UTC, Dormeh approved these changes

2023-05-15 11:35 UTC, bin-umar commented on packages/client/src/utils/formatBytes.ts
Я бы написал пару юнит тестов на эту штуку)

2023-05-15 11:38 UTC, bin-umar commented on packages/client/src/components/AvatarModalWindow/style.tsx
> +    filter: saturate(1.3);
Интересное решение! Лайк, шея))

2023-05-15 11:38 UTC, bin-umar approved these changes

2023-05-15 15:46 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +    dispatch(fetchAvatarChange(formData));
здесь как и в другим местах нужно обработать приход ошибки по сети
пример в profile
ошибку берем из store profile

2023-05-15 15:47 UTC, Dormeh commented on packages/client/src/components/AvatarModalWindow/AvatarModalWindow.tsx
> +    </StAvatarContainer>
в зависимости от того есть ошибка по сети или нет выводим снизу компонент ошибки

2023-05-15 15:56 UTC, Dormeh commented
Нужно добавить проверку ошибки после диспатча и отображение ошибки в компоненте если сервер вернет ошибку
и можно мержить

2023-05-16 09:09 UTC, merged