FC-23 Начало игры
FancyCodersYAP/UNO-fancy pull request #5
Opened 2023-03-01 15:13 UTC by we1tkindzy

Добавляет и стилизует попап "Начало игры"(components/StartGame). В дальнейшем стили будут подкорректированы.

![image](https://user-images.githubusercontent.com/58230964/222180873-b896f064-fe03-44bb-a314-4c9a20f89d65.png)

2023-03-03 18:53 UTC, Dormeh commented
@we1tkindzy Валя, подтяни себе main и сделай rebase в ветке с этой задачей с main чтобы подтянуть себе изменения от Марьяны и попробуй использовать кнопку уже из main

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
названия переменной не соответствует стайлу нужно CSSСВОЙСТВО_ТИПЭЛЕМЕНТА_ОБОЗНАЧЕНИЕВПРОЕКТЕ
посмотри как у меня названы нам ревьюер 2 раза замечания делал уже постарайся придерживаться этого стиля
в константы добавлять только те цвета которые точно не будут меняться под тему
если точно уверен что не будет меняться иначе бери из тематических файлов названия там одинаковые

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/styles/variables/colors-const.ts
>  export const COLOR_ELEMENT_ALTERNATE = '#d7dbdb';
давайте хотя бы стараться читать что ревьюер пишет каждому в ревью по PR
вчера меня просил убрать данное название)
ну и как выше писал это надо брать из цветов темы в основном в редких случаях (для переключателей каких-то) брать без переменны темы в styles/variables/colors-const
И чтобы не поднимать этот вопрос предлагаю названия переменных(констант) сначала в чате обсуждать

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/startGame.tsx
> +            <StStartGameImg src="src/assets/img/start-game-1.jpg" alt="Карточка правил" width="160px" height="160px" />
инлайн стили лучше убрать в файл со стилями возможно понадобиться в другом месте использовать компонент с другими размерами

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/startGame.tsx
> +            <StStartGameImg src="src/assets/img/start-game-2.jpg" alt="Карточка правил" width="160px" height="160px" />
и тут

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/startGame.tsx
> +            <StStartGameImg src="src/assets/img/start-game-3.jpg" alt="Карточка правил" width="160px" height="160px" />
и тут

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameText = styled.span`
для текста лучше использовать специализированный тег <p></p>

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  display: flex;
еще предлагаю сделать миксины(менять сейчас не надо) для флексов стандартных

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGame = styled.section`
не уверен что здесь надо section использовать скорее нужен компонент контейнер о котором я говорил ранее который должен быть универсальным для контента его можно сделать div  так как он для позиционирования
пока менять не нужно надо обсудить.

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  position: relative;
не понятно почему тут ты используешь position: relative/absolute
тут же все можно на display flex или grid построить?

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameImg = styled.img`
у тебя размеры картинки указаны инлайново и в компоненте тогда инлайново удали
  max-width: 160px;
  max-height: 160px;
  тоже не понятно зачем

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameButtons = styled.div`
кнопка уже есть зачем ты ее меняешь ты либо расширяй (если это прям необходимость) нашу либо с пропсами советующими использую готовую

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameLink = styled.a`
по поводу ссылки тоже надо быть понять делал ли кто может ранее если нет то оставить и добавить возможность черзе попсы установить размер шрифта

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +    opacity: 0.6;
спорный момент обычно ссылка при наведении становится ярче а не тусклее
я бы цвет поменял на более яркий из темы

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  min-width: 150px;
кнопку ограничивать не нужно она уже падингами ограничена внутри
если нет то стоит посмотреть в сторону рефакторинга самой кнопки

2023-03-07 15:32 UTC, Dormeh commented on packages/client/src/styles/variables.tsx
> +export const variables = {
этот файл по моему ранее был удален и больше не используется
проверь пожалуйста

2023-03-07 15:34 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
лучше это предварительно обсуждать так как это касается всего проекта

2023-03-07 15:36 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameImg = styled.img`
ну и есть смысл размеры width  height через пропсы задавать чтобы сделать переиспользуемым

2023-03-07 15:38 UTC, we1tkindzy commented on packages/client/src/styles/variables/colors-const.ts
>  export const COLOR_ELEMENT_ALTERNATE = '#d7dbdb';
это есть в main...

2023-03-07 15:40 UTC, we1tkindzy commented on packages/client/src/components/startGame/startGame.tsx
> +            <StStartGameImg src="src/assets/img/start-game-1.jpg" alt="Карточка правил" width="160px" height="160px" />
они у меня и в стилях прописаны, это на случай если стили отпадают, то картинки не становятся большими
если понадобится в другом месте, то можно там и поменять размеры

2023-03-07 15:41 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  position: relative;
потому что это попап поверх всей страницы

2023-03-07 15:44 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameButtons = styled.div`
это обертка

2023-03-07 15:48 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  position: relative;
лучше сразу разделить на хэдер превью и футер(условно) все запихнуть в флекс-конейнер

2023-03-07 15:49 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  min-width: 150px;
![image](https://user-images.githubusercontent.com/58230964/223474311-7f338bd6-76eb-4e0a-adbe-cc77cc928797.png)

2023-03-07 15:50 UTC, Dormeh commented on packages/client/src/styles/variables/colors-const.ts
>  export const COLOR_ELEMENT_ALTERNATE = '#d7dbdb';
было до сегодняшнего дня (
извини что приходится много раз исправлять но вчера ревьюер написал чтобы поменяли

2023-03-07 15:55 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameButtons = styled.div`
для чего она тут нужна?
как выше написал ненужно создавать кучу кнопок без необходимости

2023-03-07 15:57 UTC, Dormeh commented on packages/client/src/components/startGame/startGame.tsx
> +            <StStartGameImg src="src/assets/img/start-game-1.jpg" alt="Карточка правил" width="160px" height="160px" />
если стилей не будет то приложения тоже, сборщик их в один бандл собирает так что это не нужно тут предусматривать

2023-03-07 16:08 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  position: relative;
почему это не так? я говорил, что я делаю это как попап на главной странице без всякого отдельного роута (он здесь не нужен, даже если в какой-то игре-примере это сделано так)

2023-03-07 16:09 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameButtons = styled.div`
это не кнопка!!! 
![image](https://user-images.githubusercontent.com/58230964/223479829-68fa4f74-dbda-4b86-b5fe-6899e94c1dbc.png)

2023-03-07 16:27 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
как тогда назвать константу? COLOR_BG_... а дальше что?

2023-03-07 17:02 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
Почему ты создаешь цвет ? Hет таких цветов в константах ?

2023-03-07 17:03 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
это задний фон попапа

2023-03-07 17:08 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameButtons = styled.div`
Тогда чтобы не вводить в заблуждение нужно обозначить это либо футером либо контейнером

2023-03-07 17:27 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
он не нужен лайаут общий

2023-03-07 17:30 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BLACK_OPACITY_05};
![image](https://user-images.githubusercontent.com/58230964/223501959-9cac7bc3-3e72-4457-8baf-6dfc6a81e6ad.png)

2023-03-07 17:35 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BACKGROUND_ELEMENT_OPACITY};
background здесь не нужен тебе нужно вложить свой контейнер желтый в контейнер для контента как у Марьяны на LoginPage сделано!
У нас один лайаут, а дети разные
И я так понимаю этот элемент сам по себе тоже лишний

2023-03-07 17:38 UTC, we1tkindzy commented on packages/client/src/components/startGame/style.tsx
> +  background-color: ${COLORS.BACKGROUND_ELEMENT_OPACITY};
![image](https://user-images.githubusercontent.com/58230964/223503806-26ac2ed2-ad96-4cf5-8513-b2cf862a4e9f.png)

2023-03-07 17:39 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +  position: relative;
понял, но я представлял себе это по другому надо обсудить с командой

2023-03-07 17:46 UTC, Dormeh commented on packages/client/src/styles/variables/colors-const.ts
>  export const COLOR_ELEMENT_ALTERNATE = '#d7dbdb';
Извиняюсь это мой косяк мне казалось, что уже все поменяны были

2023-03-07 20:45 UTC, Dormeh commented on packages/client/src/components/startGame/startGame.tsx
> +const StartGame = () => {
Изначально судя из названия я думал что это компонент такой же как лидерборд, профиль, но
изучив досконально не понимю почему бы его не назвать модальным окном, если это модальное окно
либо часть которая отвечает за контент обозначить StartGame а модальное окно назавать Modal  и вынести его функционал в отдельный компонент
также и по другим частям этого компонента я бы задумался о переиспользовании в других местах приложения и назвал исходя из их назначения напрмер StImgContainer

2023-03-07 20:45 UTC, Dormeh requested changes
Изначально судя из названия я думал что это компонент такой же как лидерборд, профиль, но изучив досконально не понимаю почему бы его не назвать модальным окном, если это модальное окно либо часть которая отвечает за контент обозначить StartGame а модальное окно называть Modal и вынести его функционал в отдельный компонент также и по другим частям этого компонента я бы задумался о переиспользовании в других местах приложения и назвал исходя из их назначения например StImgContainer

2023-03-10 11:04 UTC, Dormeh reviewed
Посмотри в сторону универсальности и переиспользования кода в однотипных компонентах

2023-03-10 11:09 UTC, Dormeh commented on packages/client/src/components/startGame/style.tsx
> +export const StStartGameImgs = styled.div`
ещё можно указать что контейнер flex чтобы можно было использовать его за основу в других местах кода

2023-03-10 15:04 UTC, Dormeh approved these changes

2023-03-11 15:36 UTC, bin-umar commented on packages/client/package.json
> -    "eslint-config-prettier": "^8.5.0",
В связи с чем удалили все кришечки?

2023-03-11 15:39 UTC, bin-umar commented on packages/client/src/components/Modal/Modal.tsx
> +  );
Пропсов лучше вначале деструктуризировать:
```suggestion
  const { isOpen, title, toggle, children } = props;

  return isOpen && (
    <StModal>
      <StModalWrapper>
        <StModalTitle>{title}</StModalTitle>
        <StButtonCloseModal onClick={toggle} primary>
          X
        </StButtonCloseModal>
        <div onClick={e => e.stopPropagation()}>{children}</div>
      </StModalWrapper>
    </StModal>
  );
```

2023-03-11 15:41 UTC, bin-umar commented on packages/client/src/components/Modal/Modal.tsx
> +            <div onClick={e => e.stopPropagation()}>{props.children}</div>
JFYI, JSX не любит inline arrow functions, https://stackoverflow.com/questions/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind

2023-03-11 16:04 UTC, we1tkindzy commented on packages/client/package.json
> -    "eslint-config-prettier": "^8.5.0",
Зафиксировали версии, как учили в первом модуле, для того, чтобы не обновлялись мажорные версии пакетов

2023-03-11 16:30 UTC, bin-umar commented on packages/client/package.json
> -    "eslint-config-prettier": "^8.5.0",
Крышечка (caret) не обновляет на мажорные версии, https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004
Он обновляет только минорные/патч версии.

Обычно убирая его разработчики хотят зафиксировать версии каких либо важных зависимостей которые могут сломаться даже при обновлении на минорной версии, или ж например эта зависимость во всех проектах компании общая (допустим версия react-а) и его место обновления централизованная.
Часто бывает что лучше убирать их, да, но не всегда. 

Можно убрать все кришечки как ты сделал, в целом не вижу больших concern-ов, давай посмотрим что получится в итоге :)

2023-03-11 16:31 UTC, bin-umar approved these changes

2023-03-11 16:38 UTC, merged